version: '3'
services:
  database:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: Gimbernat
      MYSQL_USER: rofer
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: rofer1234
    ports:
      - "33060:33060"
    volumes:
      - ./db
    restart: always

  backend:
    build: './php/'
    container_name: docker-php
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    links:
      - database
